planta(retema).
planta(ricino).
planta(rosal).
planta(romero).
planta(ruda).
planta(simonillo).
planta(tamarindo).
planta(tabachín).
planta(taray).
planta(tila).


nombreCientifico(retema,spartium_junceum).
nombreCientifico(ricino,ricinus_communis).
nombreCientifico(rosal,rosa_centifolia).
nombreCientifico(romero,salvia_rosmarinus).
nombreCientifico(ruda,ruta_graveolens).
nombreCientifico(simonillo,laennecia_schiedeana).
nombreCientifico(tamarindo,tamarindus_indica).
nombreCientifico(tabachín,cesalpinea_pulcherrima).
nombreCientifico(taray,amarix_gallica).
nombreCientifico(tila,tilia_europea).

modo(interno).
modo(externo).

%--------------------------------------
afecciones(parátitos).
afecciones(hidropesía).
afecciones(acumulación_de_toxinas).
afecciones(problemas_renales).
afecciones(estreñimiento).
afecciones(peritonitis).
afecciones(lombrices).
afecciones(hernia_estrangulada).
afecciones(caída_de_cabello).
afecciones(caspa).
afecciones(seborrea).
afecciones(cólicos_infantles).
afecciones(empachos).
afecciones(conjuntivitis).
afecciones(infecciones_vaginales).
afecciones(baja_energía).
afecciones(problemas_mestruales).
afecciones(mala_digestión).
afecciones(estrés).
afecciones(partos_difíciles).
afecciones(hijos_no_deseados).
afecciones(mal_humor_en_ciclo_menstrual).
afecciones(jaquecas).
afecciones(ictericia).
afecciones(catarro_vía_biliares).
afecciones(cólico_hepático).
afecciones(dispepsia_crónica).
afecciones(sed).
afecciones(indigestión_infantil).
afecciones(hígado_intoxicado).
afecciones(riñon_intoxicado).
afecciones(cálculos_renales).
afecciones(nerviosismo).
afecciones(malestar_general).
afecciones(problemas_de_sueño).
afecciones(dolor_histérico_de_cabeza).
afecciones(fiebre).
afecciones(tos_espasmódica).

%--------------------------------------
elimina(retema,parátitos).
elimina(retema,hidropesía).
elimina(retema,acumulación_de_toxinas).
elimina(retema,problemas_renales).
elimina(ricino,estreñimiento).
elimina(ricino,peritonitis).
elimina(ricino,lombrices).
elimina(ricino,hernia_estrangulada).
elimina(ricino,parátitos).
elimina(ricino,caída_de_cabello).
elimina(ricino,caspa).
elimina(ricino,seborrea).
elimina(rosal,estreñimiento).
elimina(rosal,cólicos_infantles).
elimina(rosal,empachos).
elimina(rosal,conjuntivitis).
elimina(romero,infecciones_vaginales).
elimina(romero,baja_energía).
elimina(romero,problemas_mestruales).
elimina(romero,mala_digestión).
elimina(romero,estrés).
elimina(romero,caída_de_cabello).
elimina(ruda,partos_difíciles).
elimina(ruda,hijos_no_deseados).
elimina(ruda,mal_humor_en_ciclo_menstrual).
elimina(ruda,jaquecas).
elimina(ruda,problemas_mestruales).
elimina(simonillo,estreñimiento).
elimina(simonillo,ictericia).
elimina(simonillo,catarro_vía_biliares).
elimina(simonillo,cólico_hepático).
elimina(simonillo,dispepsia_crónica).
elimina(tamarindo,parátitos).
elimina(tamarindo,acumulación_de_toxinas).
elimina(tamarindo,problemas_renales).
elimina(tamarindo,estreñimiento).
elimina(tamarindo,sed).
elimina(tamarindo,empachos).
elimina(tamarindo,indigestión_infantil).
elimina(tabachín,hígado_intoxicado).
elimina(tabachín,riñon_intoxicado).
elimina(tabachín,hijos_no_deseados).
elimina(tabachín,problemas_mestruales).
elimina(taray,problemas_renales).
elimina(taray,cálculos_renales).
elimina(tila,nerviosismo).
elimina(tila,malestar_general).
elimina(tila,problemas_de_sueño).
elimina(tila,dolor_histérico_de_cabeza).
elimina(tila,fiebre).
elimina(tila,tos_espasmódica).
elimina(tila,estrés).


%--------------------------------------------------------

modoDeAplicacion(parátitos,interno).
modoDeAplicacion(hidropesía,interno).
modoDeAplicacion(acumulación_de_toxinas,interno).
modoDeAplicacion(problemas_renales,interno).
modoDeAplicacion(estreñimiento,interno).
modoDeAplicacion(peritonitis,interno).
modoDeAplicacion(lombrices,interno).
modoDeAplicacion(hernia_estrangulada,interno).
modoDeAplicacion(caída_de_cabello,externo).
modoDeAplicacion(caspa,externo).
modoDeAplicacion(seborrea,externo).
modoDeAplicacion(cólicos_infantles,interno).
modoDeAplicacion(empachos,interno).
modoDeAplicacion(conjuntivitis,externo).
modoDeAplicacion(infecciones_vaginales,externo).
modoDeAplicacion(baja_energía,interno).
modoDeAplicacion(problemas_mestruales,interno).
modoDeAplicacion(mala_digestión,interno).
modoDeAplicacion(estrés,interno).
modoDeAplicacion(partos_difíciles,interno).
modoDeAplicacion(hijos_no_deseados,interno).
modoDeAplicacion(mal_humor_en_ciclo_menstrual,interno).
modoDeAplicacion(jaquecas,interno).
modoDeAplicacion(ictericia,interno).
modoDeAplicacion(catarro_vía_biliares,interno).
modoDeAplicacion(cólico_hepático,interno).
modoDeAplicacion(dispepsia_crónica,interno).
modoDeAplicacion(sed,interno).
modoDeAplicacion(indigestión_infantil,interno).
modoDeAplicacion(hígado_intoxicado,interno).
modoDeAplicacion(riñon_intoxicado,interno).
modoDeAplicacion(cálculos_renales,interno).
modoDeAplicacion(nerviosismo,interno).
modoDeAplicacion(malestar_general,interno).
modoDeAplicacion(problemas_de_sueño,interno).
modoDeAplicacion(dolor_histérico_de_cabeza,interno).
modoDeAplicacion(fiebre,interno).
modoDeAplicacion(tos_espasmódica,interno).


%-----------------------------------------------

modoDePreparacion(té,parátitos).
modoDePreparacion(té,hidropesía).
modoDePreparacion(té,acumulación_de_toxinas).
modoDePreparacion(té,problemas_renales).
modoDePreparacion(té,estreñimiento).
modoDePreparacion(té,peritonitis).
modoDePreparacion(té,lombrices).
modoDePreparacion(té,hernia_estrangulada).
modoDePreparacion(aceite,caída_de_cabello).
modoDePreparacion(aceite,caspa).
modoDePreparacion(aceite,seborrea).
modoDePreparacion(infusión,cólicos_infantles).
modoDePreparacion(infusión,empachos).
modoDePreparacion(infusión,conjuntivitis).
modoDePreparacion(té,infecciones_vaginales).
modoDePreparacion(té,baja_energía).
modoDePreparacion(té,problemas_mestruales).
modoDePreparacion(té,mala_digestión).
modoDePreparacion(té,estrés).
modoDePreparacion(té,partos_difíciles).
modoDePreparacion(té,hijos_no_deseados).
modoDePreparacion(té,mal_humor_en_ciclo_menstrual).
modoDePreparacion(té,jaquecas).
modoDePreparacion(té,ictericia).
modoDePreparacion(té,catarro_vía_biliares).
modoDePreparacion(té,cólico_hepátic).
modoDePreparacion(té,dispepsia_crónica).
modoDePreparacion(agua,sed).
modoDePreparacion(agua,indigestión_infantil).
modoDePreparacion(té,hígado_intoxicado).
modoDePreparacion(té,riñon_intoxicado).
modoDePreparacion(remojo,cálculos_renales).
modoDePreparacion(té,nerviosismo).
modoDePreparacion(té,malestar_general).
modoDePreparacion(té,problemas_de_sueño).
modoDePreparacion(té,dolor_histérico_de_cabeza).
modoDePreparacion(té,fiebre).
modoDePreparacion(té,tos_espasmódica).


%---------------------------------------------------------------

aplicacion(parátitos,interno,té).
aplicacion(hidropesía,interno,té).
aplicacion(acumulación_de_toxinas,interno,té).
aplicacion(problemas_renales,interno,té).
aplicacion(estreñimiento,interno,té).
aplicacion(peritonitis,interno,té).
aplicacion(lombrices,interno,té).
aplicacion(hernia_estrangulada,interno,té).
aplicacion(caída_de_cabello,externo,aceite).
aplicacion(caspa,externo,aceite).
aplicacion(seborrea,externo,aceite).
aplicacion(cólicos_infantles,interno,infusión).
aplicacion(empachos,interno,infusión).
aplicacion(conjuntivitis,externo,infusión).
aplicacion(infecciones_vaginales,externo,té).
aplicacion(baja_energía,interno,té).
aplicacion(problemas_mestruales,interno,té).
aplicacion(mala_digestión,interno,té).
aplicacion(estrés,interno,té).
aplicacion(partos_difíciles,interno,té).
aplicacion(hijos_no_deseados,interno,té).
aplicacion(mal_humor_en_ciclo_menstrual,interno,té).
aplicacion(jaquecas,interno,té).
aplicacion(ictericia,interno,té).
aplicacion(catarro_vía_biliares,interno,té).
aplicacion(cólico_hepático,interno,té).
aplicacion(dispepsia_crónica,interno,té).
aplicacion(sed,interno,agua).
aplicacion(indigestión_infantil,interno,agua).
aplicacion(hígado_intoxicado,interno,té).
aplicacion(riñon_intoxicado,interno,té).
aplicacion(cálculos_renales,interno,remojo).
aplicacion(nerviosismo,interno,té).
aplicacion(malestar_general,interno,té).
aplicacion(problemas_de_sueño,interno,té).
aplicacion(dolor_histérico_de_cabeza,interno,té).
aplicacion(fiebre,interno,té).
aplicacion(tos_espasmódica,interno,té).


%REGLAS-------------------------------------------------------------------

recetar(AFECCIONES,PLANTA,MODO,PREPARACION):-elimina(PLANTA,AFECCIONES),aplicacion(AFECCIONES,MODO,PREPARACION).
%recetar(X,Y,interno,té).
%recetar(estreñimiento,Y,interno,té).
%recetar(partos_difíciles,X,Z,R).
%recetar(X,tila,Z,R).

alivia(AFECCIONES,PLANTA):-elimina(PLANTA,AFECCIONES).
%alivia(X,tila).
%alivia(X,tamarindo).
%alivia(ictericia,X).
%alivia(problemas_mestruales,X).

problemaInterno(AFECCIONES):-modoDeAplicacion(AFECCIONES,interno).
problemaExterno(AFECCIONES):-modoDeAplicacion(AFECCIONES,externo).
%problemaInterno(X).
%problemaExterno(Y).

usar(AFECCION,PREPARACION):-modoDePreparacion(PREPARACION,AFECCION).
%usar(estrés,X).

buscarNombreCientífico(PLANTA,CIENTIFICO):-nombreCientifico(PLANTA,CIENTIFICO).
%buscarNombreCientífico(romero,Y).

té(X):-modoDePreparacion(té,X).
aceite(X):-modoDePreparacion(aceite,X).
agua(X):-modoDePreparacion(agua,X).
infusión(X):-modoDePreparacion(infusión,X).
remojo(X):-modoDePreparacion(remojo,X).

ingerir(X,Z,Y):-elimina(X,Z),modoDeAplicacion(Z,Y).
%ingerir(ruda,X,Y).
